- name:  Disable nginx default version and enable version 24
  ansible.builtin.shell: dnf module disable nginx -y ; dnf module enable nginx:1.24 -y

- name:  install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name:  copy nginx config file
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: run app prerequisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq

- name: Start Nginx Service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true

