- name:  Copy rabbitmq repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name:  install rabbitmq server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: restart rabbitmq server service
  ansible.builtin.service:
    name: rabbitmq-server
    state: restarted

- name:  create Application User and password and privileges
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"


