- name:  install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: restart mysql service
  ansible.builtin.service:
    name: mysqld
    enabled: yes
    state: restarted

- name: set up mysql root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1


