APP_PREREQ () {

  PRINT Adding Application User
  id roboshop &>>$LOG_FILE
  if [ $? -ne 0 ]; then
  useradd roboshop &>>$LOG_FILE
  fi
  STAT $?

  PRINT remove Old Content
  rm -rf ${app_path} &>>$LOG_FILE
  STAT $?

  PRINT Create App directory
  mkdir ${app_path} &>>$LOG_FILE
  STAT $?

  PRINT Download App Content
  if [ "$component" == "dispatch" ]; then
  curl -L -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>$LOG_FILE
  else
  curl -L -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}-v3.zip &>>$LOG_FILE
  fi
  STAT $?

  PRINT Extract App Content
  cd ${app_path}
  unzip /tmp/${component}.zip &>>$LOG_FILE
  STAT $?
}