- name:  Load schema
  when: schema_type == "mongo"
  block:
    - name:  Copy MongoDB repo file
      ansible.builtin.template:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name:  Install MongoDB Client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: latest

    - name:  Load Master Data
      ansible.builtin.shell: mongosh --host mongo.{{ env }}.banecio-devops.online </app/db/master-data.js

- name:  Load schema
  when: schema_type == "mysql"
  block:
    - name:  Install mysql
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: Load schema, master data and app-user data
      ansible.builtin.shell: mysql -h mysql.{{ env }}.banecio-devops.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
      loop:
        - "schema_files"


#mysql -h mysql.dev.banecio-devops.online -uroot -pRoboShop@1 < /app/db/schema.sql
#mysql -h mysql.dev.banecio-devops.online -uroot -pRoboShop@1 < /app/db/master-data.sql
#mysql -h mysql.dev.banecio-devops.online -uroot -pRoboShop@1 < /app/db/app-user.sql






#- name: Load MySQL schema
#  when: schema == "mysql"
#  block:
#    - name: Install mysql Client
#      ansible.builtin.dnf:
#        name: mysql
#        state: latest
#
#    - name: Load Master Data
#      ansible.builtin.shell: mysql -h mysql.{{ env }}.banecio-devops.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
#      loop: "{{schema_files}}"